<table class="help-table">
	<caption><?php echo CMS_NAME; ?> tag syntax</caption>
	<tbody>
		<tr>
		<th class="tag"> Tag </th>
		<th class="desc"> Description </th>
		</tr>
		<tr>
		<td> &#91;&#42;field&#42;&#93; or &#91;&#42;TV&#42;&#93;  </td>
		<td> Inserts various blocks of content specific to the page being displayed. </td>
		</tr>
		<tr>
		<td> &#91;&#126;link&#126;&#93; </td>
		<td> Makes a link to another document in your MODx site. </td>
		</tr>
		<tr>
		<td>{{chunk}} </td>
		<td> Inserts a chunk of HTML into your page. </td>
		</tr>
		<tr>
		<td> &#91;(setting)&#93; </td>
		<td> Inserts the value of a site-wide setting named 'setting' into your page. </td>
		</tr>
		<tr>
		<td> &#91;&#91;snippet&#93;&#93; </td>
		<td> Calls a snippet cached. Inserts the output of a snippet named 'snippet' into your page </td>
		</tr>
		<tr>
		<td> &#91;&#33;snippet&#33;&#93; </td>
		<td> Calls a snippet uncached. Inserts the output of a snippet named 'snippet' into your page. </td>
		</tr>
		<tr>
		<td> &#91;&#94;timing&#94;&#93; </td>
		<td> Shows how long it took to create the current page. </td>
		</tr>
		<tr>
		<td> &#91;&#43;placeholder&#43;&#93; </td>
		<td> Acts as a placeholder for content generated by a snippet. Usually used in a chunk specified in an argument of the snippet to format the snippet's output. </td>
		</tr>
	</tbody>
</table>

