<table class="help-table">
	<caption><?php echo CMS_NAME; ?> tag syntax</caption>
	<tbody>
		<tr>
		<th class="tag"> Tag </th>
		<th class="desc"> Description </th>
		</tr>
		<tr>
		<td> &#91;&#42;field&#42;&#93; or &#91;&#42;TV&#42;&#93;  </td>
		<td> Inserts resource fields or template variables specific to the page being displayed. </td>
		</tr>
		<tr>
		<td> &#91;&#42;field@docid&#42;&#93; or &#91;&#42;TV@docid&#42;&#93;  </td>
		<td> Inserts resource fields or template variables from another page. The docid can be a docid, 'parent' or 'ultimateparent'.</td>
		</tr>
		<tr>
		<td> &#91;&#126;docid&#126;&#93; </td>
		<td> Makes a link to another document in your MODx site. </td>
		</tr>
		<tr>
		<td>{{chunk}} </td>
		<td> Inserts a chunk into your page. </td>
		</tr>
		<tr>
		<td> &#91;(setting)&#93; </td>
		<td> Inserts the value of a system setting into your page. </td>
		</tr>
		<tr>
		<td> &#91;&#91;snippet&#93;&#93; </td>
		<td> Inserts the output of a snippet into your page. If the page is cached, the result will be saved in the page's cache file.</td>
		</tr>
		<tr>
		<td> &#91;&#33;snippet&#33;&#93; </td>
		<td> Inserts the output of a snippet into your page. The snippet's output will not be cached and will be run on each page request even if the page is cached.</td>
		</tr>
		<tr>
		<td> &#91;&#94;timing&#94;&#93; </td>
		<td> Shows how long it took to create the current page. </td>
		</tr>
		<tr>
		<td> &#91;&#43;placeholder&#43;&#93; </td>
		<td> Acts as a placeholder for content generated by a snippet or plugin. Usage will be detailed in the snippet or plugins documentation.</td>
		</tr>
		<tr>
		<td> &#91;&#42;field;modifier(s)&#42;&#93;,<br />&#91;&#42;TV;modifier(s)&#42;&#93;<br />or &#91;&#43;placeholder;modifier(s)&#43;&#93;</td>
		<td> Output modifiers (strtolower, strtoupper, ucwords, ucfirst, strip_tags, urlencode, rawurlencode, html, limit(n), ellipsis(n)).</td>
		</tr>
	</tbody>
</table>

